### ISSUE TITLE
Patch doesn't work with kernel 6.0

### ISSUE THREAD

**Issue by S-h-r-i-k-e** [graysky2/kernel_compiler_patch#88] opened 2022-10-19 13:57 UTC
Hello,
Tried to apply patch more-uarches-for-kernel-5.17+.patch to vanilla kernel 6.0, 6.0.1, and 6.0.2 on distro Rocky 9 and it failed with the following:
linux-6.0.2]# patch -p1 < more-uarches-for-kernel-5.17+.patch
patching file arch/x86/Kconfig.cpu
Hunk #1 FAILED at 157.
Hunk #2 FAILED at 165.
Hunk #3 FAILED at 173.
Hunk #4 FAILED at 270.
Hunk #5 succeeded at 278 with fuzz 2.
Hunk #6 succeeded at 289 with fuzz 2.
Hunk #7 succeeded at 472 with fuzz 2.
Hunk #8 FAILED at 540.
Hunk #9 FAILED at 558.
Hunk #10 FAILED at 578.
7 out of 10 hunks FAILED -- saving rejects to file arch/x86/Kconfig.cpu.rej
patching file arch/x86/Makefile
Hunk #1 succeeded at 150 (offset 19 lines).
patching file arch/x86/include/asm/vermagic.h

**Comment by graysky2** [comment] 2022-10-19 14:10
Cannot reproduce:
```
% cd linux-6.0.2
% patch -p1 -i more-uarches-for-kernel-5.17+.patch 
patching file arch/x86/Kconfig.cpu
patching file arch/x86/Makefile
Hunk #1 succeeded at 150 (offset 19 lines).
patching file arch/x86/include/asm/vermagic.h
```

Are you sure you're patching vanilla linux and not your distro modified version?

**Comment by S-h-r-i-k-e** [comment] 2022-10-19 14:47
Correct, it is vanilla kernel from kernel.org. Additionally, just tried to do the same on Ubuntu 22.04.1 LTS with the same result. For your convenience I created a temporary Rocky 9 VM for testing:
49.12.71.127
root
24^#hFp@6fH@

**Comment by S-h-r-i-k-e** [comment] 2022-10-20 12:40
The issue was caused by me using "copy raw contents" button in browser to copy-paste content of the parch instead of downloading it with wget which resulted in additional spaces in a number of lines as shown on screenshot below. I'll leave it up to you to decide if this is an issue worth looking in to. In any case, I appreciate you quick response and a great work you do on this patch in general.

![Screenshot from 2022-10-20 15-21-48](https://user-images.githubusercontent.com/116179966/196947301-e8f2298d-5e70-4fce-b1e4-a0d3f3d0d59a.png)

**Comment by graysky2** [comment] 2022-10-20 14:20
Closing, not related to patchset.  Glad you got what you needed.

**Closed by graysky2** 2022-10-20 14:20 UTC
